//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EvaluacijaOcena.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EvaluacijaOcena.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Root&gt;
        ///&lt;List&gt;
        ///&lt;Predmet&gt;
        ///  &lt;Strategija&gt;A&lt;/Strategija&gt;
        ///  &lt;Naziv&gt;OO Projektovanje&lt;/Naziv&gt;
        ///  &lt;UsmeniMinPct&gt;50&lt;/UsmeniMinPct&gt;
        ///  &lt;UsmeniMaxPoena&gt;48&lt;/UsmeniMaxPoena&gt;
        ///  &lt;Elementi&gt;
        ///    &lt;Item&gt;
        ///      &lt;Name&gt;Pismeni&lt;/Name&gt;
        ///      &lt;Min&gt;16&lt;/Min&gt;
        ///      &lt;Max&gt;32&lt;/Max&gt;
        ///    &lt;/Item&gt;
        ///    &lt;Item&gt;
        ///      &lt;Name&gt;Lab&lt;/Name&gt;
        ///      &lt;Max&gt;20&lt;/Max&gt;
        ///    &lt;/Item&gt;
        ///  &lt;/Elementi&gt;
        ///&lt;/Predmet&gt;
        ///&lt;Predmet&gt;
        ///  &lt;Strategija&gt;A&lt;/Strategija&gt;
        ///  &lt;Naziv&gt;Rimsko pravo&lt;/Naziv&gt;
        ///  &lt;UsmeniMinPct&gt;55&lt;/UsmeniMinPct&gt;
        ///  &lt;UsmeniMaxPoena&gt;100&lt;/UsmeniMaxP [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Predmeti {
            get {
                return ResourceManager.GetString("Predmeti", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Root&gt;
        ///&lt;List&gt;
        ///&lt;Strategija&gt;
        ///  &lt;Naziv&gt;A&lt;/Naziv&gt;
        ///  &lt;Ocene&gt;
        ///    &lt;Item&gt;
        ///      &lt;Name&gt;6&lt;/Name&gt;
        ///      &lt;Min&gt;55&lt;/Min&gt;
        ///      &lt;Max&gt;64&lt;/Max&gt;
        ///    &lt;/Item&gt;
        ///    &lt;Item&gt;
        ///      &lt;Name&gt;7&lt;/Name&gt;
        ///      &lt;Min&gt;65&lt;/Min&gt;
        ///      &lt;Max&gt;74&lt;/Max&gt;
        ///    &lt;/Item&gt;
        ///    &lt;Item&gt;
        ///      &lt;Name&gt;8&lt;/Name&gt;
        ///      &lt;Min&gt;75&lt;/Min&gt;
        ///      &lt;Max&gt;84&lt;/Max&gt;
        ///    &lt;/Item&gt;
        ///    &lt;Item&gt;
        ///      &lt;Name&gt;9&lt;/Name&gt;
        ///      &lt;Min&gt;85&lt;/Min&gt;
        ///      &lt;Max&gt;94&lt;/Max&gt;
        ///    &lt;/Item&gt;
        ///    &lt;Item&gt;
        ///      &lt;Name&gt;10&lt;/Name&gt;
        ///      &lt;Min&gt;95&lt;/Min&gt;
        ///      &lt;Max&gt;100&lt;/Max&gt;
        ///    &lt;/Item&gt;    
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Strategije {
            get {
                return ResourceManager.GetString("Strategije", resourceCulture);
            }
        }
    }
}
